2024-03-03 08:02:38.430 +05:30 [INF] Here is info message from our values controller.
2024-03-03 08:02:38.469 +05:30 [DBG] Here is debug message from our values controller.
2024-03-03 08:02:38.470 +05:30 [WRN] Here is warn message from our values controller.
2024-03-03 08:02:38.473 +05:30 [ERR] Here is an error message from our values controller.
2024-03-03 11:34:39.387 +05:30 [ERR] Error - An error occurred while saving the entity changes. See the inner exception for details.,    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__112_0(DbContext _, ValueTuple`2 t)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at MysticNet8App.Infrastructure.Persistance.RepositoryManager.Save() in /Users/prakashkumar/Projects/DotnetProjects/MysticNet8App/MysticNet8App.Infrastructure/Persistance/RepositoryManager.cs:line 21
   at MysticAppNet8App.Application.Services.CompanyService.CreateCompany(Company company) in /Users/prakashkumar/Projects/DotnetProjects/MysticNet8App/MysticAppNet8App.Application/Services/CompanyService.cs:line 57
2024-03-03 11:34:39.421 +05:30 [ERR] An error occurred while creating company: An error occurred while saving the entity changes. See the inner exception for details.
2024-03-03 11:36:05.629 +05:30 [ERR] Error - An error occurred while saving the entity changes. See the inner exception for details.,    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__112_0(DbContext _, ValueTuple`2 t)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at MysticNet8App.Infrastructure.Persistance.RepositoryManager.Save() in /Users/prakashkumar/Projects/DotnetProjects/MysticNet8App/MysticNet8App.Infrastructure/Persistance/RepositoryManager.cs:line 21
   at MysticAppNet8App.Application.Services.CompanyService.CreateCompany(Company company) in /Users/prakashkumar/Projects/DotnetProjects/MysticNet8App/MysticAppNet8App.Application/Services/CompanyService.cs:line 57
2024-03-03 11:36:08.103 +05:30 [ERR] An error occurred while creating company: An error occurred while saving the entity changes. See the inner exception for details.
2024-03-03 20:33:06.581 +05:30 [ERR] Something went wrong: System.Exception: Exception of type 'System.Exception' was thrown.
   at MysticAppNet8App.Application.Services.CompanyService.GetAllCompanies(Boolean trackChanges) in /Users/prakashkumar/Projects/DotnetProjects/MysticNet8App/MysticAppNet8App.Application/Services/CompanyService.cs:line 31
   at MysticNet8App.Controllers.CompanyController.GetCompanies() in /Users/prakashkumar/Projects/DotnetProjects/MysticNet8App/MysticNet8App.API/Controllers/CompanyController.cs:line 24
   at lambda_method3(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
